var namespacegismo_1_1expr =
[
    [ "_expr< E, false >", "classgismo_1_1expr_1_1__expr_3_01E_00_01false_01_4.html", "classgismo_1_1expr_1_1__expr_3_01E_00_01false_01_4" ],
    [ "asdiag_expr", "classgismo_1_1expr_1_1asdiag__expr.html", "classgismo_1_1expr_1_1asdiag__expr" ],
    [ "cartconinv_expr", "classgismo_1_1expr_1_1cartconinv__expr.html", "classgismo_1_1expr_1_1cartconinv__expr" ],
    [ "cartcovinv_expr", "classgismo_1_1expr_1_1cartcovinv__expr.html", "classgismo_1_1expr_1_1cartcovinv__expr" ],
    [ "constMat_expr", "classgismo_1_1expr_1_1constMat__expr.html", "classgismo_1_1expr_1_1constMat__expr" ],
    [ "deriv2_expr", "classgismo_1_1expr_1_1deriv2__expr.html", "classgismo_1_1expr_1_1deriv2__expr" ],
    [ "deriv2dot_expr", "classgismo_1_1expr_1_1deriv2dot__expr.html", "classgismo_1_1expr_1_1deriv2dot__expr" ],
    [ "exp_expr", "classgismo_1_1expr_1_1exp__expr.html", "classgismo_1_1expr_1_1exp__expr" ],
    [ "flat_expr", "classgismo_1_1expr_1_1flat__expr.html", "classgismo_1_1expr_1_1flat__expr" ],
    [ "flatdot2_expr", "classgismo_1_1expr_1_1flatdot2__expr.html", "classgismo_1_1expr_1_1flatdot2__expr" ],
    [ "flatdot_expr", "classgismo_1_1expr_1_1flatdot__expr.html", "classgismo_1_1expr_1_1flatdot__expr" ],
    [ "gsFeSpace", "classgismo_1_1expr_1_1gsFeSpace.html", "classgismo_1_1expr_1_1gsFeSpace" ],
    [ "gsFeVariable", "classgismo_1_1expr_1_1gsFeVariable.html", "classgismo_1_1expr_1_1gsFeVariable" ],
    [ "idMat_expr", "classgismo_1_1expr_1_1idMat__expr.html", "classgismo_1_1expr_1_1idMat__expr" ],
    [ "integral_expr", "classgismo_1_1expr_1_1integral__expr.html", "classgismo_1_1expr_1_1integral__expr" ],
    [ "lapl_expr", "classgismo_1_1expr_1_1lapl__expr.html", "classgismo_1_1expr_1_1lapl__expr" ],
    [ "matrix_by_space_expr", "classgismo_1_1expr_1_1matrix__by__space__expr.html", "classgismo_1_1expr_1_1matrix__by__space__expr" ],
    [ "matrix_by_space_expr_tr", "classgismo_1_1expr_1_1matrix__by__space__expr__tr.html", "classgismo_1_1expr_1_1matrix__by__space__expr__tr" ],
    [ "normal_expr", "classgismo_1_1expr_1_1normal__expr.html", "classgismo_1_1expr_1_1normal__expr" ],
    [ "onormal_expr", "classgismo_1_1expr_1_1onormal__expr.html", "classgismo_1_1expr_1_1onormal__expr" ],
    [ "ovar1_expr", "classgismo_1_1expr_1_1ovar1__expr.html", "classgismo_1_1expr_1_1ovar1__expr" ],
    [ "ovar2dot_expr", "classgismo_1_1expr_1_1ovar2dot__expr.html", "classgismo_1_1expr_1_1ovar2dot__expr" ],
    [ "pow_expr", "classgismo_1_1expr_1_1pow__expr.html", "classgismo_1_1expr_1_1pow__expr" ],
    [ "ppart_expr", "classgismo_1_1expr_1_1ppart__expr.html", "classgismo_1_1expr_1_1ppart__expr" ],
    [ "ppartval_expr", "classgismo_1_1expr_1_1ppartval__expr.html", "classgismo_1_1expr_1_1ppartval__expr" ],
    [ "sign_expr", "classgismo_1_1expr_1_1sign__expr.html", "classgismo_1_1expr_1_1sign__expr" ],
    [ "tangent_expr", "classgismo_1_1expr_1_1tangent__expr.html", "classgismo_1_1expr_1_1tangent__expr" ],
    [ "tvar1_expr", "classgismo_1_1expr_1_1tvar1__expr.html", "classgismo_1_1expr_1_1tvar1__expr" ],
    [ "unitVec_expr", "classgismo_1_1expr_1_1unitVec__expr.html", "classgismo_1_1expr_1_1unitVec__expr" ],
    [ "var1_expr", "classgismo_1_1expr_1_1var1__expr.html", "classgismo_1_1expr_1_1var1__expr" ],
    [ "var2_expr", "classgismo_1_1expr_1_1var2__expr.html", "classgismo_1_1expr_1_1var2__expr" ],
    [ "var2deriv2dot_expr", "classgismo_1_1expr_1_1var2deriv2dot__expr.html", "classgismo_1_1expr_1_1var2deriv2dot__expr" ],
    [ "var2dot_expr", "classgismo_1_1expr_1_1var2dot__expr.html", "classgismo_1_1expr_1_1var2dot__expr" ]
];